# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-19 18:53
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ForeignKey',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('constraint_name', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='Schema',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('schema_name', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='Table',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('table_name', models.CharField(max_length=250)),
                ('schema', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Schema')),
            ],
        ),
        migrations.CreateModel(
            name='TableField',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field_name', models.CharField(max_length=250)),
                ('table', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Table')),
            ],
        ),
        migrations.AddField(
            model_name='foreignkey',
            name='on_table',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='on_table', to='api.Table'),
        ),
        migrations.AddField(
            model_name='foreignkey',
            name='to_table',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='to_name', to='api.Table'),
        ),
    ]
