# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-09 12:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tablefield',
            name='allow_null',
            field=models.BooleanField(default=False),
        ),
    ]
