# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-09 13:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_tablefield_allow_null'),
    ]

    operations = [
        migrations.AddField(
            model_name='tablefield',
            name='inner_type',
            field=models.CharField(default='', max_length=250),
        ),
    ]
